name: Docker CI/CD for Mercado Livre Script

on:
  push:
    branches:
      - main # O workflow será acionado em cada push para a branch 'main'
  workflow_dispatch: # Permite acionar o workflow manualmente pela UI do GitHub
  schedule:
    # Executa todos os dias à 01:00 AM UTC
    # Para ajustar o fuso horário, você pode converter para UTC ou usar um runner auto-hospedado
    # com o fuso horário configurado.
    # Exemplo: Para 01:00 AM em São Paulo (UTC-3), seria 04:00 AM UTC:
    # - cron: '0 4 * * *'
    - cron: '0 1 * * *' # Minuto Hora Dia_do_Mes Mes Dia_da_Semana

env:
  DOCKER_IMAGE_NAME: ml-product-sync # Nome da sua imagem Docker
  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }} # Usando GitHub Container Registry (GHCR)

jobs:
  build_and_push:
    runs-on: ubuntu-latest # O runner que executará as ações

    permissions:
      contents: read
      packages: write # Permissão necessária para push para GHCR

    # Definindo as variáveis de ambiente para este job, lendo dos GitHub Secrets
    env:
      CLIENT_ID: ${{ secrets.ML_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.ML_CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.ML_REFRESH_TOKEN }}
      SELLER_ID: ${{ secrets.ML_SELLER_ID }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Clona seu repositório

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Configura um builder multi-plataforma.
        # Isso é crucial para construir imagens compatíveis com diferentes arquiteturas (ex: ARM64).
        with:
          platforms: linux/amd64,linux/arm64 # Adiciona as plataformas que você deseja suportar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático fornecido pelo GitHub

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # O diretório onde o Dockerfile está (raiz do repositório)
          push: true # Faz o push da imagem para o registry
          tags: ${{ steps.meta.outputs.tags }} # Usa as tags geradas pelo metadata-action
          labels: ${{ steps.meta.outputs.labels }} # Usa os labels gerados pelo metadata-action
          # Cache para builds mais rápidos
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Adiciona a lista de plataformas para as quais a imagem será construída
          platforms: linux/amd64,linux/arm64

      - name: Verify pushed image (optional)
        run: |
          echo "Imagem Docker construída e enviada com sucesso para:"
          echo "${{ steps.meta.outputs.tags }}"

  # Job para executar o script Dockerizado em um agendamento (inalterado)
  run_scheduled_script:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'schedule'

    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dockerized Script
        run: |
          docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          docker run --rm \
            -e CLIENT_ID="${{ secrets.ML_CLIENT_ID }}" \
            -e CLIENT_SECRET="${{ secrets.ML_CLIENT_SECRET }}" \
            -e REFRESH_TOKEN="${{ secrets.ML_REFRESH_TOKEN }}" \
            -e SELLER_ID="${{ secrets.ML_SELLER_ID }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PASS="${{ secrets.DB_PASS }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest

